### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by bradleat** [serenesea/profilePage#2]
I am unable to build the project for ios:

error: /Users/bradley/dev/coding-challenge-responses/profilePage/node_modules/native-base/Fonts/rubicon-icon-font.ttf: No such file or directory

I am using OSX where should I get this font from?

**Comment by serenesea** [comment]
Thank you for the report. It's an [issue](https://github.com/GeekyAnts/NativeBase/issues/1850) of NativeBase. Library is replaced (d50443ae7d903b41ede329ce5ffbbb8c916d2a5b).
